all: install

install:
	git clone https://github.com/wincent/command-t.git | true
	git clone https://github.com/kien/ctrlp.vim.git | true
	git clone https://github.com/sjl/gundo.vim.git | true
	git clone https://github.com/itchyny/lightline.vim.git | true
	git clone https://github.com/yegappan/mru.git | true
	git clone https://github.com/scrooloose/nerdcommenter.git | true
	git clone https://github.com/scrooloose/nerdtree.git | true
	git clone https://github.com/powerline/powerline.git | true
	git clone https://github.com/vim-syntastic/syntastic.git | true
	git clone https://github.com/eugen0329/vim-esearch.git | true
	git clone https://github.com/airblade/vim-gitgutter.git | true
	git clone https://github.com/ludovicchabant/vim-gutentags.git | true
	git clone https://github.com/xolox/vim-misc.git | true
	git clone https://github.com/terryma/vim-multiple-cursors.git | true
	git clone https://github.com/jistr/vim-nerdtree-tabs.git | true
	git clone https://github.com/xolox/vim-session.git | true
	git clone https://github.com/tpope/vim-surround.git | true
	git clone https://github.com/mattn/webapi-vim.git | true